spring:
  application:
    name: payment-service
  config:
    import: "optional:configserver:http://localhost:8088"

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    #  sql:
    #    init:
    #      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: toor
    url: jdbc:mysql://localhost:33306/metro_app


