spring:
  application:
    name: ticket-service
  config:
    import: "optional:configserver:http://localhost:8088"

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    #  sql:
    #    init:
    #      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: toor
    url: jdbc:mysql://localhost:33306/metro_app

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: metro_ticket
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

